#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=l
export NEEDRESTART_SUSPEND=1
SSH_USERNAME="$(id -un)"
export SSH_USERNAME
export HELPER_SCRIPTS=/imagegeneration/helpers
export INSTALLER_SCRIPT_FOLDER=/imagegeneration/toolsets

echo "==> Running install-docker.sh"
sudo env DEBIAN_FRONTEND="${DEBIAN_FRONTEND:-}" NEEDRESTART_MODE="${NEEDRESTART_MODE:-}" NEEDRESTART_SUSPEND="${NEEDRESTART_SUSPEND:-}" GH_API_TOKEN="${GH_API_TOKEN:-}" GH_API_MIN_REMAINING="${GH_API_MIN_REMAINING:-}" GH_API_WAIT_BUFFER_SECONDS="${GH_API_WAIT_BUFFER_SECONDS:-}" GITHUB_TOKEN="${GITHUB_TOKEN:-}" SSH_USERNAME="${SSH_USERNAME:-}" HELPER_SCRIPTS="${HELPER_SCRIPTS:-}" INSTALLER_SCRIPT_FOLDER="${INSTALLER_SCRIPT_FOLDER:-}" HOME=/root bash /imagegeneration/toolsets/install-docker.sh
sudo env DEBIAN_FRONTEND="${DEBIAN_FRONTEND:-}" NEEDRESTART_MODE="${NEEDRESTART_MODE:-}" NEEDRESTART_SUSPEND="${NEEDRESTART_SUSPEND:-}" GH_API_TOKEN="${GH_API_TOKEN:-}" GH_API_MIN_REMAINING="${GH_API_MIN_REMAINING:-}" GH_API_WAIT_BUFFER_SECONDS="${GH_API_WAIT_BUFFER_SECONDS:-}" GITHUB_TOKEN="${GITHUB_TOKEN:-}" SSH_USERNAME="${SSH_USERNAME:-}" HELPER_SCRIPTS="${HELPER_SCRIPTS:-}" INSTALLER_SCRIPT_FOLDER="${INSTALLER_SCRIPT_FOLDER:-}" HOME=/root bash <<'GHA_STAGE_EOF'
set -euo pipefail
usermod -aG docker "$SSH_USERNAME"
GHA_STAGE_EOF
echo "==> Done"
