#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=l
export NEEDRESTART_SUSPEND=1
export HELPER_SCRIPTS=/imagegeneration/helpers
export INSTALLER_SCRIPT_FOLDER=/imagegeneration/toolsets
export IMAGE_VERSION=dev
export IMAGE_OS=ubuntu24-slim
export IMAGEDATA_NAME=ubuntu:24.04-slim

echo "==> Running install-ms-repos.sh"
sudo env DEBIAN_FRONTEND="${DEBIAN_FRONTEND:-}" NEEDRESTART_MODE="${NEEDRESTART_MODE:-}" NEEDRESTART_SUSPEND="${NEEDRESTART_SUSPEND:-}" GH_API_TOKEN="${GH_API_TOKEN:-}" GH_API_MIN_REMAINING="${GH_API_MIN_REMAINING:-}" GH_API_WAIT_BUFFER_SECONDS="${GH_API_WAIT_BUFFER_SECONDS:-}" GITHUB_TOKEN="${GITHUB_TOKEN:-}" SSH_USERNAME="${SSH_USERNAME:-}" HELPER_SCRIPTS="${HELPER_SCRIPTS:-}" INSTALLER_SCRIPT_FOLDER="${INSTALLER_SCRIPT_FOLDER:-}" IMAGE_VERSION="${IMAGE_VERSION:-}" IMAGE_OS="${IMAGE_OS:-}" IMAGEDATA_NAME="${IMAGEDATA_NAME:-}" HOME=/root bash /imagegeneration/build/install-ms-repos.sh
echo "==> Done"
